---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: release

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1"

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Generate token
        id: token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2
        with:
          app_id: ${{ secrets.TOKEN_EXCHANGE_APP }}
          installation_retrieval_mode: id
          installation_retrieval_payload: ${{ secrets.TOKEN_EXCHANGE_INSTALL }}
          private_key: ${{ secrets.TOKEN_EXCHANGE_KEY }}
          permissions: >-
            {"contents": "write", "packages": "write"}

      - name: Checkout source
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          token: ${{ steps.token.outputs.token }}

      - name: Install nix
        uses: cachix/install-nix-action@a809471b5c7c913aa67bec8f459a11a0decc3fce # v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Enable cachix
        uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: devenv

      - name: Write buildtime
        run: date >| .github/RELEASE

      - name: Install releaser
        run: |
          npm install -g \
            conventional-changelog-conventionalcommits@6.1.0 \
            semantic-release@23.1.1 \
            @semantic-release/changelog \
            @semantic-release/git \
            @semantic-release/exec

      - name: Run releaser
        env:
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}
        run: semantic-release

      - name: Commit changes
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9
        with:
          author_name: GitHub Actions
          author_email: github@cloudhippie.de
          add: .github/RELEASE
          message: "docs: automated release update [skip ci]"
          push: true
          commit: --signoff

...
