---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: release

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1"

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}

      - name: Install nix
        uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Enable cachix
        uses: cachix/cachix-action@v14
        with:
          name: devenv

      - name: Write buildtime
        run: date >| .github/RELEASE

      - name: Install releaser
        run: |
          npm install -g \
            conventional-changelog-conventionalcommits@6.1.0 \
            semantic-release@23.1.1 \
            @semantic-release/changelog \
            @semantic-release/git \
            @semantic-release/exec

      - name: Run releaser
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
        run: semantic-release

...
