---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: testing

"on":
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Install nix
        uses: cachix/install-nix-action@7ab6e7fd29da88e74b1e314a4ae9ac6b5cda3801 # v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Enable cachix
        uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: devenv

      - name: Update template
        run: nix develop --impure . --command scripts/generate-template

      - name: Test yamllint
        run: nix develop --impure . --command yamllint .

...
