---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: testing

"on":
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Install nix
        uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Enable cachix
        uses: cachix/cachix-action@v14
        with:
          name: devenv

      - name: Update template
        run: nix develop --impure . --command scripts/generate-template

      - name: Test yamllint
        run: nix develop --impure . --command yamllint .

...
