---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: testing

"on":
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v26

      - name: Enable cachix
        uses: cachix/cachix-action@v14
        with:
          name: devenv

      - name: Install devenv
        run: nix profile install nixpkgs#devenv

      - name: Update template
        shell: devenv shell bash -- -e {0}
        run: scripts/generate-template

...
